.gitignore, .travis.yml, fh-android-sdk/src/main/java/com/feedhenry/sdk/FH.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/FHAct.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/api/FHActRequest.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/api/FHAuthRequest.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/api/FHInitializeRequest.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/sync/FHSyncClient.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/sync/FHSyncConfig.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/sync/NotificationMessage.java, fh-android-sdk/src/main/java/com/loopj/android/http/AsyncHttpClient.java, fh-android-sdk/src/main/java/com/loopj/android/http/Base64.java, fh-android-sdk/src/main/java/com/loopj/android/http/BaseJsonHttpResponseHandler.java, fh-android-sdk/src/main/java/com/loopj/android/http/MySSLSocketFactory.java, fh-android-sdk/src/main/java/com/loopj/android/http/RequestParams.java, fh-android-sdk/src/main/java/org/json/fh/CDL.java, fh-android-sdk/src/main/java/org/json/fh/Cookie.java, fh-android-sdk/src/main/java/org/json/fh/CookieList.java, fh-android-sdk/src/main/java/org/json/fh/HTTP.java, fh-android-sdk/src/main/java/org/json/fh/HTTPTokener.java, fh-android-sdk/src/main/java/org/json/fh/JSONArray.java, fh-android-sdk/src/main/java/org/json/fh/JSONObject.java, fh-android-sdk/src/main/java/org/json/fh/JSONTokener.java, fh-android-sdk/src/main/java/org/json/fh/JSONWriter.java, fh-android-sdk/src/main/java/org/json/fh/XML.java, fh-android-sdk/src/main/java/org/json/fh/XMLTokener.java
Fix for FHMOBSDK-26. 
To test just `mvn clean install` with JDK 8
=> Javadoc fixes

fh-android-sdk-test/pom.xml, fh-android-sdk/pom.xml, pom.xml
This PR create a specific commit to tag a `2.1.0` release
=> Prepare to release

.travis.yml, fh-android-sdk/pom.xml, fh-android-sdk/src/main/java/com/feedhenry/sdk/AppProps.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/CloudProps.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/Device.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/FH.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/PushConfig.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/api/FHAuthSession.java
See: [FHMOBSDK-70](https://issues.jboss.org/browse/FHMOBSDK-70)
=> Add wrapper API for AeroGear Push

fh-android-sdk/src/main/java/com/feedhenry/sdk/FH.java
@wei-lee Just found this bug. 
Should we release 2.3.1 or add it on 2.3.0?
=> Make push methods static

fh-android-sdk/src/main/java/com/feedhenry/sdk/FH.java
@danielpassos mind to do a quick review ?
=> Removing unused class

fh-android-sdk/src/main/java/com/feedhenry/sdk/sync/FHSyncClient.java
The Android Async Http library throws a number of errors stating that asynchronous calls were not made on a thread that has called `Looper.prepare()`. This PR corrects that.
The code has also been cleaned up, with typos corrected and old links in docs updated.
Regarding the style of documentation, I've been following guidelines set out at http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html
Of note:
```
Use 3rd person (descriptive) not 2nd person (prescriptive). 
The description is in 3rd person declarative rather than 2nd person imperative.
Gets the label. (preferred)
Get the label. (avoid)
```
Future doc changes will adhere to this style.
=> Execute async requests using Looper

fh-android-sdk-test/src/main/java/com/feedhenry/sdk/tests/api/FHAuthRequestTest.java, fh-android-sdk-test/src/main/java/com/feedhenry/sdk/tests/api/FHAuthSessionTest.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/FH.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/api/FHActRequest.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/api/FHAuthRequest.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/api/FHAuthSession.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/api/FHCloudRequest.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/api/FHInitializeRequest.java
This is a set of improvements to classes in the `com.feedhenry.sdk.api` package.
Changes are similar to the ones made in #33 (updated for loops, use of `isEmpty()`, etc.), but also includes making `FHAuthSession` a static class rather than a singleton.
=> API package optimisations

fh-android-sdk/src/main/java/com/feedhenry/sdk/exceptions/FHNotReadyException.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/oauth/FHOAuthIntent.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/oauth/FHOAuthWebView.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/utils/DataManager.java
A relatively small PR this time containing a few small formatting adjustments and code optimisations.
The only noteworthy change is the correction of [this line](https://github.com/feedhenry/fh-android-sdk/compare/master...thefrontiergroup:feature/exception_oauth_package_optimisations#diff-ab893f973d888845493b29ff552e2c3cL119).
=> Exception and OAuth package optimisations

fh-android-sdk/src/main/java/com/feedhenry/sdk/FHHttpClient.java
=> Adding a Connection Timeout setting to FHHttpClient

fh-android-sdk-test/src/main/java/com/feedhenry/sdk/tests/sync/FHSyncClientTest.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/sync/FHSyncClient.java
@danielpassos @wei-lee :eyeglasses: ?
=> Fixing an edge case where FHSyncClient.destroy will crash the app

fh-android-sdk/src/main/AndroidManifest.xml
The SDK don't need to declare any specific permission
See: [RHMAP-2733](https://issues.jboss.org/browse/RHMAP-2733)
=> Remove uses-permission

fh-android-sdk-test/src/main/java/com/feedhenry/sdk/tests/api2/FHRemoteTest.java, fh-android-sdk/src/main/java/com/feedhenry/sdk2/FHAct.java, fh-android-sdk/src/main/java/com/feedhenry/sdk2/FHRemote.java
@danielpassos @wei-lee :eyes:?
=> Rhmap 2731

fh-android-sdk/src/main/AndroidManifest.xml
See: [RHMAP-2613](https://issues.jboss.org/browse/RHMAP-2613)
=> Bump minSdkVersion

fh-android-sdk/src/main/java/com/feedhenry/sdk/AppProps.java
See: [RHMAP-3108](https://issues.jboss.org/browse/RHMAP-3108)
=> Clarify load properties file

fh-android-sdk-test/src/main/java/com/feedhenry/sdk/tests/api2/FHRemoteTest.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/AppProps.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/FH.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/FHAct.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/FHHttpClient.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/FHRemote.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/api/FHActRequest.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/api/FHAuthRequest.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/api/FHAuthSession.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/api/FHCloudRequest.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/api/FHInitializeRequest.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/api2/FHAuthSession.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/exceptions/DataSetNotFound.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/sync/FHSyncClient.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/sync/FHSyncDataset.java, fh-android-sdk/src/main/java/com/feedhenry/sdk/sync/FHSyncUtils.java, fh-android-sdk/src/main/java/com/feedhenry/sdk2/FHAct.java, fh-android-sdk/src/main/java/com/feedhenry/sdk2/FHHttpClient.java, fh-android-sdk/src/main/java/com/feedhenry/sdk2/FHRemote.java
This commit narrows the exception declarations and performs minor refactors to obviate exceptions where necessary.
There is some minor API breaking so it may be important to bump the version to 4.0.0
=> Rhmap 3688

.gitignore, fh-android-sdk/pom.xml, fh-android-sdk/src/main/java/com/feedhenry/sdk/FH.java
Done for [FH-2639](https://issues.jboss.org/browse/FH-2639)
=> Using latest of AGDroid and updating Android Studio settings

fh-android-sdk/pom.xml
=> Using latst of AeroGear Android Push

fh-android-sdk/pom.xml, fh-android-sdk/src/main/java/com/feedhenry/sdk/FH.java
@matzew @matskiv @danielpassos :eyes: ?
=> Migrating to FCM

README.md, pom.xml
Using latest (non-java8) parent pom.
Tested, upload to JBoss nexus works.
@edewit @secondsun please review/merge
=> Using JBoss parent

fh-android-sdk/pom.xml
staging repo for the update is here:
https://repository.jboss.org/nexus/content/repositories/jboss_releases_staging_profile-8446/
=> Updating to bug fix version for AGDROID-560

fh-android-sdk/pom.xml, fh-android-sdk/src/main/java/com/feedhenry/sdk/FH.java
@danielpassos @matzew :eyes: 
Ping me on IRC.
=> Adding unregister method and bumping agdroid-push version

README.md, gradle-mvn-push.gradle, gradle.properties, library/build.gradle, library/gradle.properties
See: [FH-3381](https://issues.jboss.org/browse/FH-3381)
=> Add gradle release process

library/src/main/java/com/feedhenry/sdk/FH.java
I have shipped a pre-release version on Sonatype. You can use that in your test.
Add the following line in the root `build.gradle` :
```groovy
allprojects {
repositories {
jcenter()
maven { url "https://oss.sonatype.org/content/repositories/comfeedhenry-1021/" }
}
}
```
- Create a new project Hello World;
- Bump the fh-android-sdk dependency version in app/build.gradle to _3.3.2_
- Build a client Android application;
- Install and open this app in a device
- Go to Connection Tag Tab into The Build Client Tab
- Disable the connection tag
- Close the client app and open again. It should display the tag is disable
PS: It isn't going to kill. The app is displayed loading forever. There is an issue ([FH-3738](https://issues.jboss.org/browse/FH-3738)) to fix it in the in the …
=> Check if connection tags is disabled
